### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CouilleTotosXx** [Magisk-Modules-Repo/riru_lsposed#6]
Build version: 1.8.6 (6712) 
Current date: 2023-01-30T16:31:06.731910 
Device: Xiaomi M2012K11AC 
Fingerprint: Redmi/alioth/alioth:13/TKQ1.220829.002/V14.0.22.12.8.DEV:user/release-keys 
 
SDK: 33 
 
Stack trace:  
java.lang.RuntimeException: Unable to resume activity {org.lsposed.manager/org.lsposed.manager.ui.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object android.os.Parcelable$Creator.createFromParcel(android.os.Parcel)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(Unknown Source:223)
	at android.app.ActivityThread.handleResumeActivity(Unknown Source:6)
	at android.app.servertransaction.ResumeActivityItem.execute(Unknown Source:12)
	at android.app.servertransaction.ActivityTransactionItem.execute(Unknown Source:4)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(Unknown Source:32)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:79)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:172)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object android.os.Parcelable$Creator.createFromParcel(android.os.Parcel)' on a null object reference
	at io.github.xposed.xposedservice.utils.BaseParceledListSlice.<init>(Unknown Source:3)
	at io.github.xposed.xposedservice.utils.ParceledListSlice.<init>(Unknown Source:1)
	at io.github.xposed.xposedservice.utils.ParceledListSlice$a.createFromParcel(Unknown Source:1)
	at Lh.k(Unknown Source:47)
	at io.k(Unknown Source:2)
	at wl.d(Unknown Source:33)
	at wl.a(Unknown Source:14)
	at org.lsposed.manager.ui.fragment.HomeFragment.R(Unknown Source:2)
	at androidx.fragment.app.a.n(Unknown Source:4)
	at androidx.fragment.app.a.k(Unknown Source:2)
	at androidx.fragment.app.FragmentManager.R(Unknown Source:1)
	at androidx.fragment.app.FragmentManager.u(Unknown Source:3)
	at androidx.fragment.app.a.n(Unknown Source:7)
	at androidx.fragment.app.a.k(Unknown Source:2)
	at androidx.fragment.app.FragmentManager.R(Unknown Source:1)
	at androidx.fragment.app.FragmentManager.u(Unknown Source:3)
	at ee.onPostResume(Unknown Source:5)
	at r1.onPostResume(Unknown Source:0)
	at android.app.Activity.performResume(Unknown Source:170)
	at android.app.ActivityThread.performResumeActivity(Unknown Source:146)
	... 13 more

**Comment by kotori2** [comment]
https://github.com/LSPosed/LSPosed
